org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=simple_trash_slot
mod.name=Simple Trash Slot
mod.group=me.pajic
mod.version=1.0.4
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Adds an inventory slot for discarding items
mod.sources_url=https://github.com/pajicadvance/simple-trash-slot
mod.homepage_url=https://modrinth.com/mod/simple-trash-slot
mod.issues_url=https://github.com/pajicadvance/simple-trash-slot/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=aTWVHYFg
publish.curseforge=1508257
publish.github=false
